In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences 
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good devoloper',
    'understand the meening of words',
    'your videos are good'
]

In [3]:
## Define the vocebolary size 
voc_size = 10000


In [5]:
## One Hot Representetion 
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[6937, 1739, 5253, 1996],
 [6937, 1739, 5253, 2654],
 [6937, 2906, 5253, 6559],
 [8468, 8747, 8491, 5588, 356],
 [8468, 8747, 8491, 5588, 7503],
 [3482, 6937, 7396, 5253, 8083],
 [2940, 236, 6434, 5588]]

In [6]:
## word enbeding representetion 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
## make same length of each sentences using "pad_sequences"
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 6937 1739 5253 1996]
 [   0    0    0    0 6937 1739 5253 2654]
 [   0    0    0    0 6937 2906 5253 6559]
 [   0    0    0 8468 8747 8491 5588  356]
 [   0    0    0 8468 8747 8491 5588 7503]
 [   0    0    0 3482 6937 7396 5253 8083]
 [   0    0    0    0 2940  236 6434 5588]]


In [8]:
## feature representeion 
dim= 10 

In [9]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length = sent_length))
model.compile('adam','mse')

c:\Users\nahid\Desktop\DeepLearning Project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
embedded_docs[6]

array([   0,    0,    0,    0, 2940,  236, 6434, 5588])

In [22]:

model.predict(embedded_docs)[6]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[-0.00896041,  0.03839194, -0.04245327,  0.03461042,  0.03248305,
        -0.02153536, -0.04546889,  0.0405263 , -0.0169006 , -0.03589498],
       [-0.00896041,  0.03839194, -0.04245327,  0.03461042,  0.03248305,
        -0.02153536, -0.04546889,  0.0405263 , -0.0169006 , -0.03589498],
       [-0.00896041,  0.03839194, -0.04245327,  0.03461042,  0.03248305,
        -0.02153536, -0.04546889,  0.0405263 , -0.0169006 , -0.03589498],
       [-0.00896041,  0.03839194, -0.04245327,  0.03461042,  0.03248305,
        -0.02153536, -0.04546889,  0.0405263 , -0.0169006 , -0.03589498],
       [ 0.04634923,  0.01356069,  0.01745835, -0.0426463 , -0.01416421,
         0.01115442, -0.02368568,  0.01580324,  0.00721701, -0.00736158],
       [ 0.03827902, -0.0322376 , -0.04739268, -0.03800683,  0.03314686,
         0.0472669 , -0.0269522 ,  0.02702004,  0.02331586,  0.01222609],
       [-0.02338707, -0.03506687, -0.04172567,  0.02756673,  0.0453747 ,
        -0.00416028,  0.01793864, -0.04019506