In [12]:
from tensorflow.keras.preprocessing.text import one_hot


In [13]:
### sentences 
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good devoloper',
    'understand the meening of words',
    'your videos are good'
]

In [14]:
## Define the vocebolary size 
voc_size = 10000


In [15]:
## One Hot Representetion 
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2192, 4145, 5642, 8096],
 [2192, 4145, 5642, 5873],
 [2192, 8986, 5642, 3245],
 [3463, 8921, 7083, 8948, 1779],
 [3463, 8921, 7083, 8948, 955],
 [6459, 2192, 6594, 5642, 73],
 [6626, 186, 2729, 8948]]

In [16]:
## word enbeding representetion 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
## make same length of each sentences using "pad_sequences"
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='post', maxlen= sent_length)
print(embedded_docs)

[[2192 4145 5642 8096    0    0    0    0]
 [2192 4145 5642 5873    0    0    0    0]
 [2192 8986 5642 3245    0    0    0    0]
 [3463 8921 7083 8948 1779    0    0    0]
 [3463 8921 7083 8948  955    0    0    0]
 [6459 2192 6594 5642   73    0    0    0]
 [6626  186 2729 8948    0    0    0    0]]


In [18]:
## feature representeion 
dim= 10

In [19]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length = sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
embedded_docs[6]

array([6626,  186, 2729, 8948,    0,    0,    0,    0])

In [22]:

model.predict(embedded_docs)[6]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[ 0.04232914, -0.02874715,  0.00325813, -0.04200348,  0.04940108,
         0.00155518, -0.02132076,  0.00058573,  0.03517138,  0.0352384 ],
       [ 0.04136331, -0.00992665,  0.02293905, -0.03491421, -0.02039322,
         0.03556302,  0.00371804,  0.03996421,  0.01331287, -0.0482983 ],
       [-0.04655796,  0.04581714,  0.0144237 ,  0.00334974,  0.02600649,
        -0.0298769 , -0.00898115,  0.03827846,  0.00150316,  0.02955346],
       [ 0.04859242, -0.01598696,  0.02891887, -0.04590571,  0.04076967,
         0.00681757, -0.0192154 ,  0.02389343, -0.02161913, -0.04170515],
       [-0.03704059, -0.01882803, -0.02172263,  0.02332196, -0.01975521,
        -0.02533814, -0.02379539, -0.03618355,  0.02369289, -0.01788287],
       [-0.03704059, -0.01882803, -0.02172263,  0.02332196, -0.01975521,
        -0.02533814, -0.02379539, -0.03618355,  0.02369289, -0.01788287],
       [-0.03704059, -0.01882803, -0.02172263,  0.02332196, -0.01975521,
        -0.02533814, -0.02379539, -0.03618355